### ISSUE TITLE
better error handling

### ISSUE THREAD

**Issue by saberscientist** [EvolveJS/EvolveJS#36]
The library needs a significant upgrade in its ability to handle API errors from Discord. 

**Why?**
Many Discord API Errors are misrepresented as something else, and that can be *very* confusing for a user who doesn't really know what they're doing

**For example:**
![image](https://user-images.githubusercontent.com/70531349/95649598-e3e60780-0b29-11eb-8d22-5d3e3714905a.png)

Obviously, you can see that I have purposely not enabled any gateway intents. However, since the library implicitly tries to fetch all guild members anyway before `clientReady` is emitted, a chain of interesting events happen:
- the API call is made
- the library expects API to return some sort of iterable
- instead, the API returns an object with a `code` and a `message` saying "Missing Access"
- _the library still thinks that the API returned a successful result and iterates through the return value_
- node can't directly iterate through an object, and throws an unhandledRejection for each attempt to iterate (which is alot)

**The result?** 
![image](https://user-images.githubusercontent.com/70531349/95649835-6622fb80-0b2b-11eb-9e04-8bcd8f456da9.png)

`member is not iterable` is a very misleading error, and will significantly reduce the user experience for
**a)** people who don't thoroughly understand the semantics of the library
**b)** people who are working on massive projects

**Comment by Echo-3-1** [comment]
Yes, It's our fault.. now we will check before making api requests and will send proper error. Once implemented the issue will be closed.

**Comment by Echo-3-1** [comment]
Fixed in #37
